[package]
name = "mengine-quad"
version = "0.6.7"
authors = ["planet0104 <planet0104@gmail.com>"]
edition = "2021"

[dependencies]
macroquad = "0.3.10"
quad-snd = "0.2.3"
# nsvg = "0.5.1"
anyhow = "1"